services:
  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    environment:
      - API_URL=http://backend:3000  # Voorbeeld van een niet-gevoelige omgevingsvariabele

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}  # Gevoelige omgevingsvariabele voor gebruikersnaam
      - DB_PASSWORD=${DB_PASSWORD}  # Gevoelige omgevingsvariabele voor wachtwoord

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db/database.sql:/docker-entrypoint-initdb.d/create_db.sql
